### ISSUE TITLE
As a user I want to have an endpoint that gets a list of available reporting events

### ISSUE THREAD

**Issue by jared-schreibman-cdisc** [cdisc-org/analysis-results-standard#104]
Create an endpoint for /packages/{package_id}/reportingevents/

**Comment by ASL-rmarshall** [comment]
This endpoint was originally intended to return a list of references to the reporting events contained within the specified package.  However, the model currently doesn't define what a package is or include an identifier for reporting events.  If we define a package as folder containing individual reporting event files (as suggested in #99), could we rename the reporting event JSON file so that its name acts as an identifier (e.g., something list "CommonSafetyDisplays_v1.json") and have this endpoint return a list of the reporting event files in the specified package folder (for the Hackathon at least)?

Findings for the endpoint:
- The `package_id` parameter is not used (because we haven't defined what a package is)
- The endpoint returns the contents of the example reporting event instead of a list of reporting events
- The response is not a list
