### ISSUE TITLE
As a user I want to have an endpoint that returns details on a specific reporting event

### ISSUE THREAD

**Issue by jared-schreibman-cdisc** [cdisc-org/analysis-results-standard#105]

**Comment by ASL-rmarshall** [comment]
The endpoint successfully returns the entire contents of the example reporting event.

Findings:
- The original endpoint definition was for a reporting event within a specified package whereas this `/mdr/ars/reportingevents/{reportingevent_id}` endpoint implies that:
  - A search will be performed across all reporting events in all packages to return the details.
  - Either `reportingevent_id` must be unique across all packages or the endpoint will return all occurrences.
  - The response should contain the context (i.e. the package) for the returned reporting event definition(s).
- The `reportingevent_id` is currently not used (because we haven't yet decided how this should be implemented).
