### ISSUE TITLE
As a user I want to have an endpoint that returns details on a specific Reporting Event Method

### ISSUE THREAD

**Issue by jared-schreibman-cdisc** [cdisc-org/analysis-results-standard#107]

**Comment by ASL-rmarshall** [comment]
The endpoint successfully returns the details of a single method.

Findings:
- The original endpoint definition was for a method within a specified reporting event (within a specified package) whereas this `/mdr/ars/methods/{method_id}` endpoint implies that:
  - A search will be performed across all methods in all reporting events in all packages to return the details.
  - Either `method_id` must be unique across all packages and reporting events or the endpoint will return all occurrences.
  - The response should contain the context (i.e. the package and reporting event) for the returned  method definition(s).
- The `method_id` currently expects the list index number (0 for the first, 1 for the second, etc.) instead of the value of the method's `id` attribute.
- There's no error handling for invalid `method_id` values.
