### ISSUE TITLE
Utilize LinkML generated MD files to build documentation using MK Docs in "documents" folder on GitHub

### ISSUE THREAD

**Issue by bhavinbusa** [cdisc-org/analysis-results-standard#148]
This PBI is linked to the publishing of the documentation using MK Docs

**Comment by ASL-rmarshall** [comment]
@bhavinbusa @drewcdisc Looks like GitHub Pages only accepts `/ (root)` or `/docs` as a publication source.  Are you happy for me to rename `/documents` to `/docs` (which is better than having both `/documents` and `/docs`, I think)?

**Comment by ASL-rmarshall** [comment]
@bhavinbusa @drewcdisc I've decided to just create `/docs` in addition to `/documents` because the mkdocs build process clears out the folder by default which would remove the `/documents/references` sub-folder

**Comment by bhavinbusa** [comment]
Sounds good, Richard. This works, we can delete the "documents" folder
completely if needed.

**Comment by ASL-rmarshall** [comment]
I installed `mkdocs` as described [here](https://www.mkdocs.org/getting-started/#installation).

After creating a test project and installing the `mkdocs-mermaid2-plugin`, I created the [`mkdocs.yml`](https://github.com/cdisc-org/analysis-results-standard/blob/7fbcd64f403bc68ab45193bac547281d678dc162/mkdocs.yml) configuration file and updated it to reference the `project/docs` folder for the input markdown files and `docs` as the folder to build the HTML documentation.  I then ran `mkdocs build` referencing the configuration file to create the documentation.

I have added the `mkdocs build` step to the script I run after any model updates so that the documentation is kept in sync.
