### ISSUE TITLE
Modeling for using Global Titles/Footnotes/Abb/Legends across multiple displays/outputs

### ISSUE THREAD

**Issue by bhavinbusa** [cdisc-org/analysis-results-standard#25]

**Comment by bhavinbusa** [comment]
I have reviewed the model and example. It looks good to me. My only comment/question is around reference of an existing "ID" and "Global ID".  
See example below...where an ID: TrtGroup_02_1 and TrtGroup_02_2 are referenced within a WhereClause. How does the model differentiate referencing of an ID vs. a text. How does one know that an existing ID is referenced? 

          "id": "TrtGroup_02_4",
          "compoundExpression": {
            "logicalOperator": "OR",
            "whereClauses": [
              **"TrtGroup_02_1",
              "TrtGroup_02_2"**

**Comment by ASL-rmarshall** [comment]
@bhavinbusa The linkML model contains the following definition of the "whereClauses" slot:

![image](https://user-images.githubusercontent.com/113628824/211004890-cff68b23-92d4-43d9-9111-7bcec5fae2ab.png)

`range: WhereClause` means that each of the multiplue values (`multivalued: true`) must be an instance of the WhereClause class and `inlined: false` indicates that each of the values will be a reference to the identifier of an existing instance instead of a definition of a new instance.

**Comment by ASL-rmarshall** [comment]
For Sprint 4, global titles, footnotes, etc. were modelling as multiple instances of the DisplaySection class under the globalDisplaySections slot of the reportingEvent.  It's possible that this will be moved in a later release - e.g., if there are other global attributes of the reporting event, we may create something like "globalProperties" and nest the global display sections under this.

**Comment by ASL-rmarshall** [comment]
There are a couple of options for applying global display sections to a display:

1. The global definitions can be made available to be pulled into any given display as part of the design of the display.
2. Once created, global definitions could be automatically assigned to every display.

How global display sections are applied to displays will be an implementation decision and may be facilitated via APIs.
