### ISSUE TITLE
Modeling for Group of Analyses

### ISSUE THREAD

**Issue by bhavinbusa** [cdisc-org/analysis-results-standard#30]

**Comment by ASL-rmarshall** [comment]
@bhavinbusa As discussed, I have uploaded an updated version of the model that includes "listOfPlannedAnalyses" that is created using a modified version of the NestedList class that now allows an "analysis" to be specified (as a reference to an instance of an "Analysis" class) in the same way that an "output" can be specified (as a reference to an instance of an "Output" class).

These changes have also be represented in the updated cmap.

A "Group of Analyses" is "sublist" within the "listOfPlannedAnalyses".

I have also updated the example yaml/json files to include a "listOfPlannedAnalyses" based on the CDISC Pilot SAP.  A few of the analyses in the STUDY POPULATION section have references to defined analyses (defined in the new "analyses" attribute of the ReportingEvent), but these definitions are not complete yet - they currently only include id and version, and (when needed) references to an analysis set and grouping.

**Comment by ASL-rmarshall** [comment]
It seems that there is no set/defined specification for the types of categorization of analyses/outputs that might be necessary.  The following are a few examples of ways in which analyses/outputs might be categorized:
- "Group of Analyses"
  - Population Description
  - Safety
  - Efficacy
- "Analysis Type", which seems to be an indication of the domain for the source data
  - Demographics
  - Adverse Events
  - Vital Signs
- Source data class (as this might affect the types of analyses that are expected)
  - Events
  - Findings
  - Subject-level?
- Type of analysis (some of which might only be applicable to certain classes of input data) and may indicate the structure of analysis dataset expected/required (e.g., BDS, OCCDS, TTE, etc)
  - Occurrence
  - Time to event
  - Change from baseline
  - Shift table
- Importance for CSR
  - Top-line analysis
  - Other
- Estimand Analysis Type
  - Primary Estimator
  - Sensitivity Analysis
  - Supplementary Analysis

It will be difficult to include specific representations of the categorizations in the model without having a clear idea of how categorization is performed and how the categories are used/interpreted.  However, in order to allow categorization to be applied, I have added "analysisCategorizations" as an attribute of the ReportingEvent with a structure that allows id and label to be defined for each categorization, and for each category within the categorization.  I have also included "subCategorizations" within Category to allow nested categorizations to be defined.  I have also added "categoryRefs" as a multi-valued attribute for both analyses and outputs, which will allow multiple categories to be referenced.

**Comment by ASL-rmarshall** [comment]
Examples files have been uploaded showing definition and use of analysis categories:
- **[cdiscpilot01-sprint6.yaml](https://github.com/cdisc-org/analysis-results-standard/blob/cd00ac5e791fabcf5249d27bd13b8d27e7d71552/workfiles/examples/cdiscpilot01-sprint6.yaml)** 
-  **[cdiscpilot01-sprint6.json](https://github.com/cdisc-org/analysis-results-standard/blob/cd00ac5e791fabcf5249d27bd13b8d27e7d71552/workfiles/examples/cdiscpilot01-sprint6.json)**

The following categorizations/sub-categorizations are defined in the example files:
- Categorization: Group of Analyses
  - Category: Population Description
  - Category: Safety
  - Category: Efficacy
 - Categorization: Analysis Data Class
   - Category: Subject-level
     - Sub-categorization: Subject-level Data Type
       - Category: Demographics
   - Category: Events
     - Sub-categorization: Events Data Type
       - Category: Adverse Events
       - Category: Clinical Events
       - Category: Disposition
     - Sub-categorization: Events Analysis Type
       - Category: Occurrence
       - Category: Time-to-Event
   - Category: Findings
     - Sub-categorization: Findings Data Type
       - Category: Vital Signs
       - Category: Laboratory Tests
     - Sub-categorization: Findings Analysis Type
       - Category: Change from Baseline
       - Category: Shift Table
 - Categorization: Estimand Analysis Type
   - Category: Primary Estimator
   - Category: Sensitivity Analysis
   - Category: Supplementary Analysis

To show how these would be used, references to some of these categories have been added for the first defined analysis and the first defined output.
