### ISSUE TITLE
Add Comparative Statistics (e.g. P value) to existing Demographics and AE SOC PT tables and generate metadata

### ISSUE THREAD

**Issue by bhavinbusa** [cdisc-org/analysis-results-standard#40]
We will take existing demographics and AE SOC PT shells and add comparative statistics and test out how the model handles adding comparative statistics.  Any learnings from this PBI will need update to the model.

**Comment by ASL-rmarshall** [comment]
Analyses representing comparative statistics were added for demography, AE SOC PT and to correspond with the first analysis in the AE summary (subjects with any TEAE).  Three new analysis methods were defined, each reporting just a p-value:
- Pearson's chi-squared test for comparison of categorical variables by treatment in the demography analyses
- ANOVA for comparison of continuous variables by treatment in the demography analyses
- Fisher's exact test for comparison of subjects with TEAEs in the AE analyses.

To keep things simple, comparative statistics were all defined as separate analyses and the only change that was made to the model was to add a `resultsByGroup` attribute to the `OrderedGroupingFactor` class. The `resultsByGroup` attribute is boolean and is used to indicate whether a separate analysis result is expected for each group in the grouping factor (used in the analysis).  This approach was chosen because any of the following situations can occur:
- A separate result is expected for each of the groups in **all** groupings defined for the analysis.
- Separate results are not expected for the groups in **any** of the groupings defined for the analysis.
- A separate result is expected for each of the grouping **some** of the groupings defined for the analysis, **but not others**.

I've uploaded [Sprint 12 Examples.xlsx](https://github.com/cdisc-org/analysis-results-standard/blob/fe4fa85487399d2011505fae4a7ba7e909567041/workfiles/examples/Sprint%2012%20Examples.xlsx), which contains the updated metadata but the Demog/AE SOCPT shell and display sheets haven't been updated yet.  However, I've updated:
- the load program to convert the updated Excel file to YAML (see [Sprint 12 Examples.yaml](https://github.com/cdisc-org/analysis-results-standard/blob/fe4fa85487399d2011505fae4a7ba7e909567041/workfiles/examples/Sprint%2012%20Examples.yaml) and its conversion to [Sprint 12 Examples.json](https://github.com/cdisc-org/analysis-results-standard/blob/fe4fa85487399d2011505fae4a7ba7e909567041/workfiles/examples/Sprint%2012%20Examples.json))
- the lopa program to generate a human-readable description of the analyses, including the indication of whether results are expected for each group in each grouping used in the analysis (see [Sprint 12 Examples-LOPA.txt](https://github.com/cdisc-org/analysis-results-standard/blob/fe4fa85487399d2011505fae4a7ba7e909567041/workfiles/examples/Sprint%2012%20Examples-LOPA.txt))
