### ISSUE TITLE
As an analysis designer I want to see Documentation, Reason and Purpose elements in the ARS model, as are appropriate

### ISSUE THREAD

**Issue by bhavinbusa** [cdisc-org/analysis-results-standard#43]
Documentation, Reason and Purpose is part of the existing ARM model. We will evaluate if we need these elements in the new ARS model and if so, we will add.

**Comment by ASL-rmarshall** [comment]
@bhavinbusa I uploaded the updated model and corresponding renditions.  These are the changes that I made for this PBI:
- Added the following slots to the `ReportingEvent` class:
  - `referenceDocuments`: can contain one or more instances of the new `ReferenceDocument` class, which allows specification of the `id`, `name` and `location` of a reference document used in the reporting event (such as a protocol, SAP, or CSR, or a file containing programming code).
  - `terminologyExtensions`: can contain one or more instances of the new `TerminologyExtension` class, which allows any of a predefined set of ARS enumerations to be extended.  A new instance of the `TerminologyExtension` class would be created for each enumeration being extended (as indicated by the value of the `enumeration` slot) with new sponsor-defined terms being added to the `sponsorTerms` slot as instances of the `SponsorTerm` class (which includes `id`, `submissionValue` and `description` slots).  Each newly defined sponsor term can then be referenced by id instead of using one of the permission values from the defined enumeration.
- Added new enumerations:
  - `AnalysisReason`: based on the Define-XML terminology, C117744
  - `AnalysisPurpose`: (based on the Define-XML terminology, C117745
  - `PageRefType`: based on the Define-XML allowable values for PDFPageRef@Type
  - `ExtensibleTerminology`: a list of the extensible enumerations used in the ARS model (used as the range for the `enumeration` slot in the `TerminologyExtension` class)
- Added the following slots to the `Analysis` class:
  - `reason`: can be either a value from the `AnalysisReason` enumeration or a reference to an instance of the `SponsorTerm` class.
  -  `purpose` can be either a value from the `AnalysisPurpose` enumeration or a reference to an instance of the `SponsorTerm` class.
  - `documentRefs`: can be one or more instances for the new `DocumentRef` class, which includes a reference to one of the reference documents defined for the reporting event (`referenceDocumentId`) and zero or more `pageRefs`, each of which is an instance of the new `PageRef` class or one of its "flavours":
    - `PageNumberListRef` which constrains `refType` to be "PhysicalRef" and `pages` to be one or more instances of the new `PageNumberList` class, which just contains an `integer` `pageNumbers` slot.
    - `PageNumberRangeRef` which constrains `refType` to be "PhysicalRef" and `pages` to be one or more instances of the new `PageNumberRange` class, which contains `integer` `firstPage` and `lastPage` slots.
    - `PageNameRef` which constrains `refType` to be "NamedDestination" and `pages` to be one or more instances of the new `PageNameList` class, which just contains an `string` `pageNames` slot.
